Repository pyapp-kit/magicgui, pull requests merged in 2023-10, with the labels that each got.

#590 feat: support python3.12
  .github/workflows/test_and_deploy.yml
  pyproject.toml
Labels: enhancement

#583 fix: Fix parent attribute to point to proper magicgui widget parent
  src/magicgui/backends/_ipynb/widgets.py
  src/magicgui/backends/_qtpy/widgets.py
  tests/test_container.py
  tests/test_widgets.py
Labels: bug

#546 fix: prevent dupe calls, alternative
  src/magicgui/type_map/_type_map.py
  tests/conftest.py
  tests/test_magicgui.py
  tests/test_types.py
Labels: bug

#600 chore: preserve magicgui-decorated function parameter hints with ParamSpec
  src/magicgui/type_map/_magicgui.py
  src/magicgui/types.py
  src/magicgui/widgets/_function_gui.py
Labels: typing
